version: "3.7"

services:
  db:
    image: postgres
    container_name: rostov-2025-db
    env_file:
      - .env
    ports:
      - "4545:5432"

  app:
    build:
      context: .
    container_name: rostov-2025-app
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    restart: always
    ports:
      - "8081:8000"
    depends_on:
      - db
